#Route User
indexUser:
   path: /user/viewAdmin
   controller: App\Controller\UserController::index
addUser:
  path: /user/new
  controller: App\Controller\UserController::signup
editUser:
  path: /user/edit/{id}
  controller: App\Controller\UserController::edit
showUser:
  path: /user/show/{id}
  controller: App\Controller\UserController::show
deleteUser:
  path: /user/delete/{id}
  controller: App\Controller\UserController::delete
login:
  path: /login
  controller: App\Controller\UserController::login
logout:
  path: /logout
  controller: App\Controller\UserController::logout

#Route Produit
home:
  path: /
  controller: App\Controller\ProduitController::index

#Route Panier



#Route ContenuPanier
