#Route User
#ADMIN
users:
  path: /admin/user
  controller: App\Controller\UserController::index
deleteUser:
  path: /admin/delete/{id}
  controller: App\Controller\UserController::delete
#USER
addUser:
  path: /sign-up
  controller: App\Controller\UserController::signup
editUser:
  path: /user/edit/{id}
  controller: App\Controller\UserController::edit
showUser:
  path: /user/show/{id}
  controller: App\Controller\UserController::show
login:
  path: /login
  controller: App\Controller\UserController::login
logout:
  path: /logout
  controller: App\Controller\UserController::logout

#Route Produit
#ADMIN
home:
  path: /
  controller: App\Controller\ProduitController::index
#USER

#Route Panier
#ADMIN
#USER

#Route ContenuPanier
#ADMIN
#USER
