
#Route User
indexUser:
   path: /
   controller: App\Controller\UserController::index
addUser:
  path: /user/new
  controller: App\Controller\UserController::delete
deleteUser:
  path: /user/delete/{id}
  controller: App\Controller\UserController::delete
login:
  path: /login
  controller: App\Controller\UserController::login
logout:
  path: /logout
  controller: App\Controller\UserController::logout

#Route Produit

#Route Panier

#Route ContenuPanier
